# Generated by Django 3.1.2 on 2020-11-03 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_income',
            old_name='recieved_date',
            new_name='received_date',
        ),
    ]
