# Generated by Django 3.1.2 on 2020-11-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
