# Generated by Django 3.1.2 on 2020-11-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_project_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
