# Generated by Django 3.1.2 on 2020-10-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20201030_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.BooleanField(default='1'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.BooleanField(default='1'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='status',
            field=models.BooleanField(default='1'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.BooleanField(default='1'),
        ),
    ]
