# Generated by Django 3.1.2 on 2020-11-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_tax_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='year',
            field=models.DateField(),
        ),
    ]
