# Generated by Django 3.1.2 on 2020-11-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20201120_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='enquiry_follow_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
