# Generated by Django 3.1.2 on 2020-11-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_enquiry_enquiry_follow_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='enquiry_follow_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
