# Generated by Django 3.1.2 on 2020-10-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20201030_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='status',
            field=models.BooleanField(default='False'),
        ),
    ]
