# Generated by Django 3.1.2 on 2020-10-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_remove_followup_imp_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='status',
            field=models.BooleanField(default='1'),
        ),
    ]
