# Generated by Django 3.1.2 on 2021-01-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('0', 'Female'), ('1', 'Male')], max_length=11),
        ),
        migrations.AlterField(
            model_name='employee',
            name='residence_address',
            field=models.CharField(max_length=500),
        ),
    ]
