# Generated by Django 3.1.2 on 2020-11-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_salary',
            name='total_salary',
            field=models.IntegerField(default='0'),
        ),
    ]
