# Generated by Django 3.1.2 on 2020-11-23 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20201123_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_salary',
            name='total_salary',
            field=models.FloatField(default='0'),
        ),
    ]
