# Generated by Django 3.1.2 on 2020-10-30 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20201030_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sallary_increament',
            name='employe_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
    ]
