# Generated by Django 3.1.2 on 2020-10-30 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20201030_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='employee_name',
            new_name='employe_name',
        ),
    ]
