# Generated by Django 3.1.2 on 2020-12-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email_id',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
